version: '3'

services:

  influxdb:
    command: influxd
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=mydb
    image: influxdb
    networks:
      - influx-net
    ports:
      - 8086:8086
      - 2003:2003

  grafana:
    command: run
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - influx-net
    depends_on:
      - influxdb

networks:
  influx-net:
    driver: bridge
